agile:
  kaptcha:
    enable: true
    url: /code
  security:
    enable: false
    error-sign:
      count-timeout: 1m
      enable: true
      lock-for-expiration: true
      lock-time: 3m
      lock-type: account,ip,session_id
      max-error-count: 5
    exclude-url: ${agile.kaptcha.url},/swagger-ui.html,/webjars/springfox-swagger-ui/*,/v2/api-docs,/swagger-resources/**,/api/password-find
    fail-forward-url: /fail
    login-out-url: /api/logout
    login-password: password
    login-url: /api/login
    login-username: username
    password:
      algorithm-model: AES/CBC/PKCS5Padding
      duration: 31d
      key: 167223764989834
      offset: 3612213421341234
      strength: 5
      strength-conf:
        max-length: 32
        weight-of-key-word: 0.35
        weight-of-key-words: password,iloveyou,sunshine,1314,520,a1b2c3,admin
        weight-of-regex: 0.65
        weight-of-regex-map:
          - regex: (?:([\da-zA-Z])\1{2,})
            weight: 0.4
          - regex: (?:([\da-zA-Z])\1+){2,}
            weight: 0.15
          - regex: ([\da-zA-Z]{2,})\1+
            weight: 0.12
          - regex: ((?:0(?=1)|1(?=2)|2(?=3)|3(?=4)|4(?=5)|5(?=6)|6(?=7)|7(?=8)|8(?=9)){2,}+\d)|((?:9(?=8)|8(?=7)|7(?=6)|6(?=5)|5(?=4)|4(?=3)|3(?=2)|2(?=1)|1(?=0)){2,}+\d)
            weight: 0.2
          - regex: ((?:a(?=b)|b(?=c)|c(?=d)|d(?=e)|e(?=f)|f(?=g)|g(?=h)|h(?=i)|i(?=j)|j(?=k)|k(?=l)|l(?=m)|m(?=n)|n(?=o)|o(?=p)|p(?=q)|q(?=r)|r(?=s)|s(?=t)|t(?=u)|u(?=v)|v(?=w)|w(?=x)|x(?=y)|y(?=z)){2,}+[a-z])|((?:A(?=B)|B(?=C)|C(?=D)|D(?=E)|E(?=F)|F(?=G)|G(?=H)|H(?=I)|I(?=J)|J(?=K)|K(?=L)|L(?=M)|M(?=N)|N(?=O)|O(?=P)|P(?=Q)|Q(?=R)|R(?=S)|S(?=T)|T(?=U)|U(?=V)|V(?=W)|W(?=X)|X(?=Y)|Y(?=Z)){2,}+[A-Z])
            weight: 0.18
          - regex: ((?:q(?=w)|w(?=e)|e(?=r)|r(?=t)|t(?=y)|y(?=u)|u(?=i)|i(?=o)|o(?=p)){2,}+[a-z])|((?:Q(?=W)|W(?=E)|E(?=R)|R(?=T)|T(?=Y)|Y(?=U)|U(?=I)|I(?=O)|O(?=P)){2,}+[A-Z])|((?:a(?=s)|s(?=d)|d(?=f)|f(?=g)|g(?=h)|h(?=j)|j(?=k)|k(?=l)){2,}+[a-z])|((?:A(?=S)|S(?=D)|D(?=F)|F(?=G)|G(?=H)|H(?=J)|J(?=K)|K(?=L)){2,}+[A-Z])|((?:z(?=x)|x(?=c)|c(?=v)|v(?=b)|b(?=n)|n(?=m)){2,}+[a-z])|((?:Z(?=X)|X(?=C)|C(?=V)|V(?=B)|B(?=N)|N(?=M)){2,}+[A-Z])
            weight: 0.1
          - regex: ((((19|20)\d{2})-(0?[13-9]|1[012])-(0?[1-9]|[12]\d|30))|(((19|20)\d{2})-(0?[13578]|1[02])-31)|(((19|20)\d{2})-0?2-(0?[1-9]|1\d|2[0-8]))|((((19|20)([13579][26]|[2468][048]|0[48]))|(2000))-0?2-29))
            weight: 0.3
    real-ip-header: X-Real-Ip
    success-forward-url: /success
    success-logout-forward-url: /logout-success
    token-header: authToken
    token-secret: 23617641641
    token-timeout: 30m
    token-transmission-mode: cookie,header
    token-type: easy
    verification-code: authCode
  simulation:
    enable: false
    user: '{"username":"admin2","password":"$2a$04$H5Zj6JmtZRyyrVKKMsJmO.txNXcRQNWxo5C.d0KoijnlqCbGdi0fq","enabled":true,"accountNonExpired":true,"accountNonLocked":false,"credentialsNonExpired":true,"authorities":[],"loginStrategy":"MORE"}'
    user-class: cloud.agileframework.security.filter.login.InMemoryUserDetails
